"""create

Revision ID: 44763cb579d7
Revises: 
Create Date: 2025-11-21 01:54:03.941771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44763cb579d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender'), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('fitness_level', postgresql.ENUM('beginner', 'intermediate', 'advance', name='fitnesslevel'), nullable=True),
    sa.Column('fitness_goal', postgresql.ENUM('lose_weight', 'build_muscle', 'improve_endurance', 'general_fitness', name='fitnessgoal'), nullable=True),
    sa.Column('work_out_location', postgresql.ENUM('home_workout', 'gym_workout', 'both', name='workoutlocation'), nullable=True),
    sa.Column('days_availability', sa.ARRAY(postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayavailability')), nullable=True),
    sa.Column('equipment_availability', sa.ARRAY(postgresql.ENUM('bodyweight', 'dumbells', 'resistance_bands', 'kettleballs', 'pull_up_bars', 'yoga_mat', 'full_gym_access', name='equipmentavailability')), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='fitness'
    )
    op.create_table('workout_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('notes_from_coach', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['fitness.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fitness'
    )
    op.create_table('workout_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_sequence', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_day_type', postgresql.ENUM('workout', 'rest', name='workoutdaytype'), nullable=False),
    sa.Column('workout_program_id', sa.Integer(), nullable=False),
    sa.Column('workout_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workout_program_id'], ['fitness.workout_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fitness'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_days', schema='fitness')
    op.drop_table('workout_programs', schema='fitness')
    op.drop_table('users', schema='fitness')
    # ### end Alembic commands ###
